<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="1" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="19213" started-at="2015-06-17T08:49:39Z" finished-at="2015-06-17T08:49:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="19213" started-at="2015-06-17T08:49:39Z" finished-at="2015-06-17T08:49:58Z">
      <class name="Cashier.DepositTest">
        <test-method status="PASS" signature="initLogs()[pri:0, instance:Cashier.DepositTest@4149888e]" name="initLogs" is-config="true" duration-ms="27" started-at="2015-06-17T09:49:39Z" finished-at="2015-06-17T09:49:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initLogs -->
        <test-method status="FAIL" signature="DepositTest(java.util.Hashtable)[pri:0, instance:Cashier.DepositTest@4149888e]" name="DepositTest" duration-ms="18101" started-at="2015-06-17T09:49:39Z" data-provider="CashierDataProvider" finished-at="2015-06-17T09:49:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Card=111.0, Amount=3.0, Runmode=Y, PromCodes=, Cvv2=123.0, Expected_Result=FAILURE, Browser=Chrome, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at org.openqa.selenium.support.ui.FluentWait.<init>(FluentWait.java:94)
	at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:70)
	at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:44)
	at Cashier.DepositTest.DepositTest(DepositTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DepositTest -->
        <test-method status="SKIP" signature="DepositTest(java.util.Hashtable)[pri:0, instance:Cashier.DepositTest@4149888e]" name="DepositTest" duration-ms="94" started-at="2015-06-17T09:49:57Z" data-provider="CashierDataProvider" finished-at="2015-06-17T09:49:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Card=111.0, Amount=20.0, Runmode=N, PromCodes=, Cvv2=12.0, Expected_Result=FAILURE, Browser=Chrome, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test DepositTest inside the suite Cashier]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test DepositTest inside the suite Cashier
	at Base.TestBase.validateRunmodes(TestBase.java:94)
	at Cashier.DepositTest.DepositTest(DepositTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DepositTest -->
        <test-method status="SKIP" signature="DepositTest(java.util.Hashtable)[pri:0, instance:Cashier.DepositTest@4149888e]" name="DepositTest" duration-ms="90" started-at="2015-06-17T09:49:57Z" data-provider="CashierDataProvider" finished-at="2015-06-17T09:49:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Card=2257.0, Amount=20.0, Runmode=N, PromCodes=, Cvv2=123.0, Expected_Result=FAILURE, Browser=Chrome, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test DepositTest inside the suite Cashier]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test DepositTest inside the suite Cashier
	at Base.TestBase.validateRunmodes(TestBase.java:94)
	at Cashier.DepositTest.DepositTest(DepositTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DepositTest -->
        <test-method status="SKIP" signature="DepositTest(java.util.Hashtable)[pri:0, instance:Cashier.DepositTest@4149888e]" name="DepositTest" duration-ms="92" started-at="2015-06-17T09:49:58Z" data-provider="CashierDataProvider" finished-at="2015-06-17T09:49:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Card=111.0, Amount=20.0, Runmode=N, PromCodes=Bonse120, Cvv2=123.0, Expected_Result=FAILURE, Browser=Chrome, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test DepositTest inside the suite Cashier]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test DepositTest inside the suite Cashier
	at Base.TestBase.validateRunmodes(TestBase.java:94)
	at Cashier.DepositTest.DepositTest(DepositTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DepositTest -->
        <test-method status="SKIP" signature="DepositTest(java.util.Hashtable)[pri:0, instance:Cashier.DepositTest@4149888e]" name="DepositTest" duration-ms="95" started-at="2015-06-17T09:49:58Z" data-provider="CashierDataProvider" finished-at="2015-06-17T09:49:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Card=111.0, Amount=20.0, Runmode=N, PromCodes=, Cvv2=123.0, Expected_Result=SUCCESS, Browser=Chrome, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test DepositTest inside the suite Cashier]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test DepositTest inside the suite Cashier
	at Base.TestBase.validateRunmodes(TestBase.java:94)
	at Cashier.DepositTest.DepositTest(DepositTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DepositTest -->
      </class> <!-- Cashier.DepositTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
